let encargo = [{
    "idEncargo":1,
    "idUsuarioCreador":1,
    "idIntitucion":1,
    "idEstado":1,
    "idTipo":1,
    "idUsuarioResponsable":1,
    "fechaCierreEncargo":Date,
    "descripcionEncargo":"Hola Buenas Tardes",
    "fechaCreacionEncargo":Date,
},{ 
    "idEncargo":2,
    "idUsuarioCreador":2,
    "idIntitucion":2,
    "idEstado":2,
    "idTipo":2,
    "idUsuarioResponsable":2,
    "fechaCierreEncargo":Date,
    "descripcionEncargo":"Hola Buenas Noches",
    "fechaCreacionEncargo":Date,
},{
    "idEncargo":3,
    "idUsuarioCreador":3,
    "idIntitucion":3,
    "idEstado":3,
    "idTipo":3,
    "idUsuarioResponsable":3,
    "fechaCierreEncargo":Date,
    "descripcionEncargo":"Hola Buenos Dias",
    "fechaCreacionEncargo":Date,
},{
    "idEncargo":4,
    "idUsuarioCreador":4,
    "idIntitucion":4,
    "idEstado":4,
    "idTipo":4,
    "idUsuarioResponsable":4,
    "fechaCierreEncargo":Date,
    "descripcionEncargo":"Hola Buenas",
    "fechaCreacionEncargo":Date,
},]