let lstencargo = [
	{
		idEncargo: 1,
		tituloEncargo: "Este es el primer ejemplo",
		idUsuarioCreador: 1,
		idIntitucion: 1,
		idEstado: 1,
		idTipo: 1,
		idUsuarioResponsable: 1,
		fechaCierreEncargo: Date,
		descripcionEncargo: "Este es el primer encargo de prueba",
		fechaCreacionEncargo: Date,
	},
	{
		idEncargo: 2,
		tituloEncargo: "Este es el primer ejemplo",
		idUsuarioCreador: 2,
		idIntitucion: 2,
		idEstado: 2,
		idTipo: 2,
		idUsuarioResponsable: 2,
		fechaCierreEncargo: Date,
		descripcionEncargo: "Este es el segundo encargo de prueba",
		fechaCreacionEncargo: Date,
	},
	{
		idEncargo: 3,
		tituloEncargo: "Este es el primer ejemplo",
		idUsuarioCreador: 3,
		idIntitucion: 3,
		idEstado: 3,
		idTipo: 3,
		idUsuarioResponsable: 3,
		fechaCierreEncargo: Date,
		descripcionEncargo: "Este es el tercer encargo de prueba",
		fechaCreacionEncargo: Date,
	},
	{
		idEncargo: 4,
		tituloEncargo: "Este es el primer ejemplo",
		idUsuarioCreador: 4,
		idIntitucion: 4,
		idEstado: 4,
		idTipo: 4,
		idUsuarioResponsable: 4,
		fechaCierreEncargo: Date,
		descripcionEncargo: "Este es el cuarto encargo de prueba",
		fechaCreacionEncargo: Date,
	},
];
export { lstencargo };
